export type Theme = 'light' | 'dark' | 'system';

export const pantoneColors = {
  classicBlue: '#0F4C75',
  classicBlueLight: '#3282B8',
  coolGray11: '#53565A',
  coolGray8: '#6D6E71',
  coolGray5: '#B1B3B3',
  coolGray2: '#D0D0CE',
  coolGray1: '#E5E6E4',
  white: '#FFFFFF',
  black: '#1C1C1B',
  reflexBlue: '#001489',
  processBlue: '#0085CA',
  warmGray11: '#5C5855',
  warmGray8: '#8B8680',
  warmGray5: '#BEB8B0',
  warmGray2: '#E3DFD7',
  red032: '#EF3340',
  green: '#00A859',
  orange021: '#FE5000',
} as const;

export const themeConfig = {
  light: {
    background: pantoneColors.white,
    foreground: pantoneColors.black,
    card: pantoneColors.white,
    cardForeground: pantoneColors.black,
    primary: pantoneColors.classicBlue,
    primaryForeground: pantoneColors.white,
    secondary: pantoneColors.coolGray11,
    secondaryForeground: pantoneColors.white,
    muted: pantoneColors.coolGray1,
    mutedForeground: pantoneColors.coolGray8,
    accent: pantoneColors.coolGray2,
    accentForeground: pantoneColors.black,
    border: pantoneColors.coolGray2,
    input: pantoneColors.coolGray2,
    ring: pantoneColors.classicBlue,
    destructive: pantoneColors.red032,
    destructiveForeground: pantoneColors.white,
    success: pantoneColors.green,
    successForeground: pantoneColors.white,
    warning: pantoneColors.orange021,
    warningForeground: pantoneColors.white,
  },
  dark: {
    background: pantoneColors.black,
    foreground: pantoneColors.coolGray1,
    card: pantoneColors.coolGray11,
    cardForeground: pantoneColors.coolGray1,
    primary: pantoneColors.classicBlueLight,
    primaryForeground: pantoneColors.white,
    secondary: pantoneColors.coolGray8,
    secondaryForeground: pantoneColors.white,
    muted: pantoneColors.coolGray11,
    mutedForeground: pantoneColors.coolGray5,
    accent: pantoneColors.warmGray11,
    accentForeground: pantoneColors.coolGray1,
    border: pantoneColors.warmGray11,
    input: pantoneColors.warmGray11,
    ring: pantoneColors.classicBlueLight,
    destructive: pantoneColors.red032,
    destructiveForeground: pantoneColors.white,
    success: pantoneColors.green,
    successForeground: pantoneColors.white,
    warning: pantoneColors.orange021,
    warningForeground: pantoneColors.white,
  },
} as const;

export const getThemeColors = (theme: 'light' | 'dark') => themeConfig[theme];
